# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: backend
                  image: valross132/devops-backend:latest
                  ports:
                      - containerPort: 3000
                        name: http
                  env:
                      - name: DATABASE_HOST
                        value: db
                      - name: DATABASE_PORT
                        value: "15432"
                      - name: DATABASE_NAME
                        value: devopsdb
                      - name: DATABASE_USER
                        value: valross132
                      - name: DATABASE_PASSWORD
                        value: "712132666"
                      - name: POD_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                  resources:
                      requests:
                          cpu: "100m"
                      limits:
                          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
    name: backend
spec:
    selector:
        app: backend
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
          nodePort: 32000
    type: NodePort
