# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: backend
                  image: valross132/devops-backend:latest
                  ports:
                      - containerPort: 3000
                  resources:
                      requests:
                          cpu: "100m"
                      limits:
                          cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
    name: backend
spec:
    selector:
        app: backend
    ports:
        - protocol: TCP
          port: 80
          targetPort: 3000
    type: ClusterIP
