services:

  db: 
    image: postgres:13
    container_name: db
    restart: always
    env_file:
      - backend/.env
    environment:
      POSTGRES_USER: valross132
      POSTGRES_PASSWORD: 712132666
      POSTGRES_DB: devopsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

  backend:
    build: ./backend
    ports: 
      - "4200:4200"
    env_file:
      - backend/.env
    command: npm run dev
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data: