apiVersion: batch/v1
kind: Job
metadata:
    name: k6-loadtest
spec:
    template:
        spec:
            containers:
                - name: k6
                  image: grafana/k6
                  command: ["k6", "run", "/test/loadtest.js"]
                  volumeMounts:
                      - name: k6-script
                        mountPath: /test
            volumes:
                - name: k6-script
                  configMap:
                      name: k6-loadtest
            restartPolicy: Never
