apiVersion: v1
kind: Service
metadata:
    name: kube-state-metrics
    namespace: kube-system
    labels:
        app: kube-state-metrics
spec:
    selector:
        app: kube-state-metrics
    ports:
        - name: http
          port: 8080
          targetPort: 8080
    type: ClusterIP
