apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-exporter
    namespace: monitoring
    labels:
        app: nginx-exporter
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx-exporter
    template:
        metadata:
            labels:
                app: nginx-exporter
        spec:
            containers:
                - name: nginx-exporter
                  image: nginx/nginx-prometheus-exporter:latest
                  ports:
                      - containerPort: 9113
---
apiVersion: v1
kind: Service
metadata:
    name: nginx-exporter
    namespace: monitoring
spec:
    selector:
        app: nginx-exporter
    ports:
        - protocol: TCP
          port: 9113
          targetPort: 9113
