apiVersion: v1
kind: Service
metadata:
    name: node-exporter
    namespace: monitoring
    labels:
        app.kubernetes.io/name: node-exporter
spec:
    selector:
        app.kubernetes.io/name: node-exporter
    ports:
        - name: metrics
          port: 9100
          targetPort: 9100
    type: ClusterIP
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: node-exporter
    namespace: monitoring
    labels:
        app.kubernetes.io/name: node-exporter
spec:
    selector:
        matchLabels:
            app.kubernetes.io/name: node-exporter
    template:
        metadata:
            labels:
                app.kubernetes.io/name: node-exporter
        spec:
            containers:
                - name: node-exporter
                  image: quay.io/prometheus/node-exporter:v1.8.1
                  ports:
                      - containerPort: 9100
                        name: metrics
                  resources:
                      limits:
                          cpu: 100m
                          memory: 128Mi
                      requests:
                          cpu: 50m
                          memory: 64Mi
                  securityContext:
                      privileged: true
                  volumeMounts:
                      - name: proc
                        mountPath: /host/proc
                        readOnly: true
                      - name: sys
                        mountPath: /host/sys
                        readOnly: true
            hostNetwork: true
            volumes:
                - name: proc
                  hostPath:
                      path: /proc
                - name: sys
                  hostPath:
                      path: /sys
