apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: backend-nodejs-podmonitor # Уникальное имя для вашего PodMonitor
    namespace: default # Namespace, где находится ваш Node.js бэкенд
    labels:
        release: prometheus # Это критично! Должен совпадать с именем вашего Helm-релиза kube-prometheus-stack
spec:
    selector:
        matchLabels:
            app: backend # Лейбл, который есть на ваших подах бэкенда
    podMetricsEndpoints:
        - port:
              http # Имя порта, которое вы используете в контейнере вашего пода для метрик.
              # Убедитесь, что это имя (не номер) порта из вашего Deployment.
              # Если у вас нет имени, используйте containerPort: 8080 (или ваш порт) и удалите 'port:'
          path: /metrics # Путь к эндпоинту метрик (у вас уже /metrics)
          interval: 10s # Интервал скрапинга
          relabelings:
              - sourceLabels: [__meta_kubernetes_pod_name]
                targetLabel: pod
                action: replace
              - sourceLabels: [__meta_kubernetes_pod_label_app]
                targetLabel: app
                action: replace
              - targetLabel: job
                replacement: "nodejs-backend" # Ваше имя job, которое вы использовали ранее
                action: replace
              - sourceLabels: [__meta_kubernetes_pod_name]
                targetLabel: instance
                action: replace
