global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: "kubernetes-apiservers"
      kubernetes_sd_configs:
          - role: endpoints
      scheme: https
      tls_config:
          insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
          - source_labels:
                [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: default;kubernetes;https

    - job_name: "kubernetes-nodes"
      kubernetes_sd_configs:
          - role: node
      scheme: https
      tls_config:
          insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: node

    - job_name: "kubernetes-nodes-cadvisor"
      kubernetes_sd_configs:
          - role: node
      scheme: https
      metrics_path: /metrics/cadvisor
      tls_config:
          insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: $1:10250
            source_labels: [__meta_kubernetes_node_name]
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: node

    - job_name: "kubernetes-pods"
      kubernetes_sd_configs:
          - role: pod
      relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_pod_label_app]
            regex: backend
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

    - job_name: "backend-pods"
      kubernetes_sd_configs:
          - role: pod
      relabel_configs:
          - action: keep
            source_labels: [__meta_kubernetes_pod_label_app]
            regex: backend
          - action: keep
            source_labels: [__meta_kubernetes_namespace]
            regex: default
          - action: keep
            source_labels: [__meta_kubernetes_pod_container_port_name]
            regex: http
          - action: replace
            source_labels: [__address__]
            regex: (.*):.*
            replacement: $1:3000
            target_label: __address__
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: instance
            replacement: $1
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
            replacement: $1
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
            replacement: $1
          - action: replace
            source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
            replacement: $1
          - action: replace
            source_labels: [__meta_kubernetes_pod_label_job]
            target_label: job
            replacement: $1
      metrics_path: /metrics
      scheme: http
