apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: backend-servicemonitor
    labels:
        release: prometheus # ("prometheus" или "kube-prometheus-stack")
spec:
    selector:
        matchLabels:
            app: backend
    endpoints:
        - port: http
          path: /metrics
          interval: 10s
