apiVersion: apps/v1
kind: Deployment
metadata:
    name: sonarqube
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: sonarqube
    template:
        metadata:
            labels:
                app: sonarqube
        spec:
            securityContext:
                fsGroup: 1000
            containers:
                - name: sonarqube
                  image: sonarqube:community
                  ports:
                      - containerPort: 9000
                  env:
                      - name: SONAR_ES_BOOTSTRAP_CHECKS_DISABLE
                        value: "true"
                  volumeMounts:
                      - name: sonarqube-data
                        mountPath: /opt/sonarqube/data
                  securityContext:
                      runAsUser: 1000
                      runAsGroup: 1000
                  resources:
                      requests:
                          memory: "2Gi"
                          cpu: "1"
                      limits:
                          memory: "4Gi"
                          cpu: "2"
            volumes:
                - name: sonarqube-data
                  persistentVolumeClaim:
                      claimName: sonarqube-pvc
